version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: sysadm-postgres
    environment:
      POSTGRES_DB: sysadmDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    networks:
      - network

  api:
    build: ./api
    container_name: sysadm-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sysadmDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - "19000:8080"
      - "19007:8787"
    restart: always
    depends_on:
      - postgres
    networks:
      - network

  site:
    container_name: sysadm-site
    build:
      context: ./site
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./site:/site
    networks:
      - network
    depends_on:
      - api
    restart: always

  init-db:
    build:
      context: ./site
      dockerfile: Dockerfile
    container_name: sysadm-init-db
    command: ["/site/wait-for-it.sh", "sysadm-api:8080", "--", "python", "insert_fake_data.py"]
    depends_on:
      - api
    networks:
      - network
    environment:
      WAIT_HOSTS: api:8080

networks:
  network:
